@Library('SnykShared@master')                                                                                                           
import com.symphony.security.containers.Artifactory


node {

    def snyk_image = 'slex-reg-test/snyk-release:experimental'
    def artifactory_url = 'artifact.symphony.com'
    stage('Hello World') {
        echo 'hello World'
        sh 'pwd'
        sh 'docker --version'
    }

    stage('Test with Docker') {
        echo 'test with docker'
        sh 'docker run --rm -i alpine:3.13 cat /etc/os-release'
        
    }

    stage('get stuff') {
        artfactory = new Artifactory(this)
        artfactory.pull(snyk_image)

        sh "docker run --rm -i ${artifactory_url}/${snyk_image} cat /etc/os-release"
    }
}

        
